name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node.js with Node v22 and install pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 22 
          cache: 'pnpm'

      # Install pnpm (latest compatible version)
      - name: Install pnpm
        run: npm install -g pnpm@9.12.2  

      # Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Install additional testing tools
      - name: Install Cypress
        run: pnpm exec cypress install

      - name: Install Playwright
        run: pnpm exec playwright install

      # Set up affected SHAs for Nx
      - uses: nrwl/nx-set-shas@v4

      # Run affected Nx tasks
      - name: Nx Affected Tasks
        run: pnpm exec nx affected -t lint test build e2e
